### ISSUE TITLE
[Update] Affinity and toleration not respected

### ISSUE THREAD

**Issue by Alegrowin** [vulcanlink/charts#10]
affinity: {
  enabled: false
},
toleration: {
  enabled: false
}

It is fixed in the apache/openwhisk repo =>
https://github.com/apache/openwhisk-deploy-kube/pull/606

**Comment by leovigna** [comment]
Thanks, I replaced it with a submodule pointing to apache/openwhisk so Vulcan Link will continue getting updates. Unfortunately this breaks the flat structure with each directory being a helm chart but I think I can live with that.
https://github.com/vulcanlink/charts/pull/12
