### ISSUE TITLE
Add default nodeselector geth

### ISSUE THREAD

**Issue by tthebst** [vulcanlink/charts#24]
The [documentation](https://artifacthub.io/packages/helm/vulcanlink/geth) describes the node labeling but the ETH chart does not respect that labeling and it has to be provided manually through the nodeselector value. I think this behavior is unexpected.

I can add it if you want.

**Comment by leovigna** [comment]
Thanks for pointing this out. Should be fixed in latest master branch. 
Default `values.yaml` now has
```
nodeSelector:
  geth/role: node
 ```
